[package]
name = "sidewinder"
version = "0.1.0"
edition = "2021"
description = "Rust path tracer."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/tedbyron/sidewinder"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["graphics", "3d", "ray-tracing", "path-tracing", "rendering"]
categories = ["rendering", "rendering::engine", "multimedia"]

[dependencies]
indicatif = "0.17.0-beta.1"
# parking_lot = "0.11.2"
