[package]
name = "sidewinder"
version = "0.1.0"
edition = "2021"
description = "Path tracer in Rust."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/tedbyron/sidewinder"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["graphics", "3d", "ray-tracing", "path-tracing", "rendering"]
categories = ["rendering", "rendering::engine", "multimedia"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.0-beta.1"
